### ISSUE TITLE
Incorrect meta schema validation tests

### ISSUE THREAD

**Issue by bugventure** [epoberezkin/json-schema-consolidate#1]
The possible reason most validators fail the metaschema validation tests is because your supposedly valid objects contain `id` fields that are not valid `URI`s according to [RFC3986](http://tools.ietf.org/html/rfc3986#section-3). According to the URI spec, a valid URI must start with a scheme followed by `://`.

This requirement for the `id` field is enforced by the [JSON metaschema](http://json-schema.org/schema) that enforces the URI format on the `id` field in a schema object.

Failing validators seem to observe the RFC3986 spec more strictly when validating URIs.

**Comment by epoberezkin** [comment]
You are right, thanks for noticing.
Strange though that is-my-json-valid only accepts short uri fragments in schemas passed via options and at the same time requires URIs to be full in schema IDs.
I will correct.
